/**
 * Central icon resolver.
 * Priority: Icons8 (PNG, colorful, interactive) → Hishabee (SVG) → Lucide (handled by caller).
 */

// ─── ICONS8 maps ────────────────────────────────────────────────────────────

export const ICONS8_BY_URL: Record<string, string> = {
  // Admin
  "/dashboard": "business",
  "/dashboard/billing-overview": "combo-chart",
  "/dashboard/olt-overview": "pie-chart",
  "/dashboard/website": "website",
  "/dashboard/billing": "documents",
  "/dashboard/billing/list": "documents",
  "/dashboard/billing/daily-collection": "coins",
  "/dashboard/billing/cashbox": "coins",
  "/dashboard/billing/expense": "profit",
  "/dashboard/billing/due": "high-priority",
  "/dashboard/billing/transactions": "data-transfer",
  "/dashboard/billing/recurring": "sync",
  "/dashboard/billing/printer": "print",
  "/dashboard/billing/invoices": "folder-invoices",
  "/dashboard/clients": "people",
  "/dashboard/clients/list": "people",
  "/dashboard/clients/new": "add-user-male",
  "/dashboard/clients/new-request": "address-book",
  "/dashboard/clients/expired": "high-priority",
  "/dashboard/clients/active": "checked",
  "/dashboard/clients/inactive": "cancel",
  "/dashboard/clients/recycle": "reset",
  "/dashboard/clients/map": "map-marker",
  "/dashboard/reports": "bar-chart",
  "/dashboard/reports/sales": "positive-dynamic",
  "/dashboard/reports/collection": "coins",
  "/dashboard/reports/customers": "people",
  "/dashboard/reports/inventory": "stack",
  "/dashboard/inventory": "stack",
  "/dashboard/inventory/items": "stack",
  "/dashboard/inventory/categories": "opened-folder",
  "/dashboard/inventory/stock": "warehouse",
  "/dashboard/inventory/transfers": "delivery",
  "/dashboard/purchase": "shopping-mall",
  "/dashboard/purchase/orders": "purchase-order",
  "/dashboard/purchase/suppliers": "factory",
  "/dashboard/sales": "profit",
  "/dashboard/sales/quick": "delivery-time",
  "/dashboard/sales/invoices": "folder-invoices",
  "/dashboard/hr": "manager",
  "/dashboard/hr/employees": "people",
  "/dashboard/hr/attendance": "today",
  "/dashboard/hr/leave": "calendar",
  "/dashboard/hr/payroll": "coins",
  "/dashboard/hr/shifts": "schedule",
  "/dashboard/hr/overtime": "overtime",
  "/dashboard/olt": "server",
  "/dashboard/olt/devices": "router-symbol",
  "/dashboard/olt/onu": "wi-fi-router",
  "/dashboard/olt/alerts": "high-priority",
  "/dashboard/network": "internet",
  "/dashboard/network/monitoring": "internet",
  "/dashboard/network/diagram": "flow-chart",
  "/dashboard/network/devices": "router-symbol",
  "/dashboard/support": "online-support",
  "/dashboard/support/tickets": "online-support",
  "/dashboard/support/new": "add-folder",
  "/dashboard/tasks": "tasks",
  "/dashboard/tasks/list": "to-do-list",
  "/dashboard/tasks/board": "checklist",
  "/dashboard/sms": "comments",
  "/dashboard/sms/send": "sms",
  "/dashboard/sms/templates": "documents",
  "/dashboard/sms/history": "timeline",
  "/dashboard/notice": "news",
  "/dashboard/notice/list": "news",
  "/dashboard/notice/new": "megaphone",
  "/dashboard/settings": "settings",
  "/dashboard/settings/profile": "manager",
  "/dashboard/settings/company": "organization",
  "/dashboard/settings/branches": "city-buildings",
  "/dashboard/settings/users": "people",
  "/dashboard/settings/roles": "shield",
  "/dashboard/settings/security": "lock",
  "/dashboard/settings/backup": "cloud-sync",
  "/dashboard/accounting": "calculator",
  "/dashboard/accounting/ledger": "address-book",
  "/dashboard/accounting/journal": "documents",
  "/dashboard/accounting/cashbook": "coins",
  "/dashboard/assets": "guarantee",
  "/dashboard/assets/list": "guarantee",
  "/dashboard/assets/assignments": "approval",
  "/dashboard/vas": "stack",
  "/dashboard/ecommerce": "shop",
  "/dashboard/ecommerce/products": "stack",
  "/dashboard/ecommerce/orders": "delivery-time",
  "/dashboard/training": "training",
  "/dashboard/warranty": "warranty",
  "/dashboard/website/dashboard": "website",
  "/dashboard/website/pages": "opened-folder",
  "/dashboard/website/notices": "news",
  "/dashboard/website/offers": "discount",
  "/dashboard/website/menu": "menu",
  "/dashboard/website/media": "gallery",
  "/dashboard/website/settings": "settings",
  "/dashboard/accounting/transactions": "data-transfer",
  "/dashboard/config/locations": "map-marker",
  "/dashboard/config/divisions": "map-marker",
  "/dashboard/config/districts": "address",
  "/dashboard/support/categories": "opened-folder",

  // Client Portal
  "/portal/dashboard": "business",
  "/portal/profile": "manager",
  "/portal/bills": "documents",
  "/portal/invoices": "folder-invoices",
  "/portal/ledger": "address-book",
  "/portal/support": "online-support",
  "/portal/notices": "news",
  "/portal/messages": "comments",
  "/portal/live-usage": "data-transfer",
  "/portal/speed-test": "increase",
  "/portal/shop": "shopping-mall",
  "/portal/my-orders": "delivery-time",
  "/portal/media": "shared-folder",
  "/portal/change-request": "process",
  "/portal/settings": "settings",

  // POP / Reseller
  "/pop-admin/dashboard": "business",
  "/pop-admin/notes": "documents",
  "/pop-admin/billing/list": "documents",
  "/pop-admin/billing/daily-collection": "coins",
  "/pop-admin/billing/expense": "profit",
  "/pop-admin/billing/due": "high-priority",
  "/pop-admin/clients": "people",
  "/pop-admin/clients/new": "add-user-male",
  "/pop-admin/clients/add": "add-user-male",
  "/pop-admin/clients/bulk-import": "upload",
  "/pop-admin/clients/left": "cancel",
  "/pop-admin/clients/scheduler": "calendar",
  "/pop-admin/clients/active": "checked",
  "/pop-admin/clients/inactive": "cancel",
  "/pop-admin/config/zones": "map-marker",
  "/pop-admin/config/sub-zones": "address",
  "/pop-admin/config/boxes": "opened-folder",
  "/pop-admin/config/packages": "stack",
  "/pop-admin/config/districts": "map-marker",
  "/pop-admin/config/upazilas": "address",
  "/pop-admin/config/departments": "organization",
  "/pop-admin/config/designations": "approval",
  "/pop-admin/config/devices": "router-symbol",
  "/pop-admin/mikrotik-users": "server",
  "/pop-admin/mikrotik-users/bulk-create": "upload",
  "/pop-admin/employees": "people",
  "/pop-admin/employees/add": "add-user-male",
  "/pop-admin/employees/salary-sheet": "money",
  "/pop-admin/monitoring/online": "wi-fi-connected",
  "/pop-admin/monitoring/offline": "wi-fi",
  "/pop-admin/tickets": "online-support",
  "/pop-admin/tickets/new": "add-folder",
  "/pop-admin/reports": "bar-chart",
  "/pop-admin/reports/bill-collection": "coins",
  "/pop-admin/reports/customer": "people",
  "/pop-admin/reports/enable-disable": "sync",
  "/pop-admin/reports/messages": "comments",
  "/pop-admin/reports/due-sms": "high-priority",
  "/pop-admin/reports/discount": "discount",
  "/pop-admin/reports/processing-fee": "coins",
  "/pop-admin/reports/btrc": "combo-chart",
  "/pop-admin/reports/financial": "pie-chart",
  "/pop-admin/settings": "settings",
  "/pop-admin/sms": "comments",
  "/pop-admin/sms/templates": "documents",
  "/pop-admin/sms/individual": "people",
  "/pop-admin/sms/send": "sms",
  "/pop-admin/sms/gateway": "server",
  "/pop-admin/sms/telegram": "comments",
  "/pop-admin/notice": "news",
  "/pop-admin/system/setup": "administrative-tools",
  "/pop-admin/system/bill-period": "calendar",
  "/pop-admin/system/period": "schedule",
  "/pop-admin/system/invoice": "folder-invoices",
  "/pop-admin/system/email": "comments",
  "/pop-admin/system/payment-gateways": "coins",
  "/pop-admin/system/processing-fee": "coins",
  "/pop-admin/system/automatic-process": "process",
  "/pop-admin/system/activity-log": "timeline",
  "/pop-admin/accounting/income": "profit",
  "/pop-admin/accounting/expense": "high-priority",
  "/pop-admin/accounting/cashbook": "calculator",
  "/pop-admin/fund-history/credit": "positive-dynamic",
  "/pop-admin/fund-history/debit": "data-transfer",
};

export const ICONS8_BY_LABEL: Record<string, string> = {
  "ড্যাশবোর্ড": "business",
  "ওয়েবসাইট প্যানেল": "website",
  "কনফিগারেশন": "administrative-tools",
  "VAS": "stack",
  "হোম ক্লায়েন্ট": "people",
  "POP / MAC ক্লায়েন্ট": "mac-client",
  "ব্যান্ডউইথ ক্লায়েন্ট": "data-transfer",
  "ডিভাইস": "router-symbol",
  "HR ও পেরোল": "manager",
  "OLT ম্যানেজমেন্ট": "server",
  "নেটওয়ার্ক মনিটরিং": "internet",
  "নেটওয়ার্ক ডায়াগ্রাম": "flow-chart",
  "ছুটি ম্যানেজমেন্ট": "schedule",
  "ইভেন্ট ও ছুটি": "calendar",
  "সাপোর্ট ও টিকেটিং": "online-support",
  "টাস্ক ম্যানেজমেন্ট": "tasks",
  "ব্যান্ডউইথ ক্রয়": "data-transfer",
  "ক্রয়": "shopping-mall",
  "বিক্রয় ও সার্ভিস": "profit",
  "ইনভেন্টরি": "stack",
  "অ্যাসেট": "guarantee",
  "অ্যাকাউন্টিং": "calculator",
  "রিপোর্ট": "bar-chart",
  "SMS সার্ভিস": "comments",
  "ই-কমার্স": "shop",
  "সিস্টেম": "settings",
  "নিরাপত্তা": "shield",
  "ব্যাকআপ": "cloud-sync",
  "নোটিশ ও বিজ্ঞপ্তি": "megaphone",
  "যোগাযোগ": "address-book",
  "ফাইল ও ডকুমেন্ট": "opened-folder",
  "ব্রাঞ্চ": "city-buildings",
  "লজিস্টিক্স": "truck",
  "মাইক্রোটিক ক্লায়েন্ট": "mac-client",
  "কর্মচারী": "people",
  "ক্লায়েন্ট": "people",
  "মনিটরিং": "internet",
  "সাপোর্ট টিকেট": "online-support",
  "এসএমএস সার্ভিস": "comments",
  "হিসাব": "calculator",
  "ফান্ড হিস্ট্রি": "timeline",
};

export const ICONS8_BY_TITLE: Record<string, string> = {
  // Common
  "ড্যাশবোর্ড": "business",
  "হোম": "home",
  "ক্যাশবক্স": "coins",
  "এক্সপেন্স": "profit",
  "খরচ": "profit",
  "বকেয়া": "high-priority",
  "লেনদেন": "data-transfer",
  "প্রোডাক্ট": "stack",
  "পণ্য তালিকা": "stack",
  "স্টক": "warehouse",
  "প্রিন্টার": "print",
  "প্রিন্ট": "print",
  "SMS মার্কেটিং": "comments",
  "অনলাইন শপ": "shop",
  "ই-কমার্স": "shop",
  "ট্রেনিং": "training",
  "ওয়ারেন্টি": "warranty",
  "রিসাইকেল বিন": "reset",
  "মেয়াদোত্তীর্ণ": "high-priority",
  "সাবস্ক্রিপশন": "approval",
  "কুইক সেল": "delivery-time",
  "দ্রুত বিক্রয়": "delivery-time",
  "ক্রয় তালিকা": "purchase-order",
  "কেনার তালিকা": "purchase-order",
  "বিজনেস ওভারভিউ": "combo-chart",
  "কোম্পানি ওভারভিউ": "organization",
  "কন্টাক্ট": "contact-card",
  "যোগাযোগ": "address-book",
  "সেটিংস": "settings",
  "সার্চ": "search",
  "ফিল্টার": "filter",
  "এডিট": "edit",
  "মুছুন": "trash",
  "ডিলিট": "trash",
  "যোগ করুন": "plus-math",
  "নতুন": "plus-math",
  "ডাউনলোড": "download",
  "আপলোড": "upload",
  "কপি": "copy",
  "সাহায্য": "help",
  "তথ্য": "info",
  "ক্যালকুলেটর": "calculator",
  "ক্যালেন্ডার": "calendar",
  "সময়সূচি": "schedule",
  "অ্যালার্ম": "alarm-clock",
  "টাইমলাইন": "timeline",
  "ছুটি": "calendar",
  "ওভারটাইম": "overtime",
  "উপস্থিতি": "today",
  "অ্যাটেনডেন্স": "today",
  "শিফট": "schedule",
  "এমপ্লয়ি": "people",
  "কর্মচারী": "people",
  "পেরোল": "coins",
  "বেতন": "money",
  "বোনাস": "gift",
  "ডিসকাউন্ট": "discount",
  "মূল্য": "price-tag",
  "PDF": "pdf",
  "ফাইল": "opened-folder",
  "ফোল্ডার": "opened-folder",
  "ইনভয়েস ফোল্ডার": "folder-invoices",
  "আর্কাইভ": "archive-folder",
  "ব্রাঞ্চ": "city-buildings",
  "শাখা": "city-buildings",
  "ব্যাংক": "bank-building",
  "হাসপাতাল": "hospital-3",
  "স্কুল": "school-building",
  "ফ্যাক্টরি": "factory",
  "গুদাম": "warehouse",
  "ওয়্যারহাউস": "warehouse",
  "ট্রাক": "truck",
  "ডেলিভারি": "delivery",
  "গাড়ি": "car",
  "মোটরসাইকেল": "motorcycle",
  "জ্বালানি": "gas-station",
  "অবস্থান": "map-marker",
  "ম্যাপ": "map-marker",
  "ঠিকানা": "address",
  "কম্পাস": "compass",
  "প্লে": "play",
  "পজ": "pause",
  "স্টপ": "stop-squared",
  "রেকর্ড": "record",
  "ফরওয়ার্ড": "forward",
  "টু-ডু": "to-do-list",
  "চেকলিস্ট": "checklist",
  "চুক্তি": "approval",
  "পাসওয়ার্ড": "lock",
  "লক": "lock",
  "নিরাপত্তা": "shield",
  "ফিঙ্গারপ্রিন্ট": "fingerprint",
  "QR কোড": "qr-code",
  "বারকোড": "barcode",
  "মেগাফোন": "megaphone",
  "মাইক্রোফোন": "microphone",
  "ক্যামেরা": "camera",
  "গ্যালারি": "gallery",
  "ছবি": "image",
  "মেসেজ পাঠান": "sms",
  "কল": "office-phone",
  "ভলিউম": "ringer-volume",
  "তারকা": "star",
  "ট্রফি": "trophy",
  "টার্গেট": "target",
  "লক্ষ্য": "goal",
  "ব্যবহারকারী": "user",
  "ইউজার": "user",
  "প্রোফাইল": "manager",
  "আমার প্রোফাইল": "manager",
  "নতুন ইউজার": "add-user-male",
  "ইউজার যোগ": "add-user-male",
  "নোটিফিকেশন": "notification",
  "নোটিশ": "news",
  "মেসেজ": "comments",
  "মাসিক বিল": "documents",
  "ইনভয়েস": "folder-invoices",
  "লেজার": "address-book",
  "আমার লেজার": "address-book",
  "শপ": "shopping-mall",
  "আমার অর্ডার": "delivery-time",
  "সাপোর্ট টিকেট": "online-support",
  "টিকেট": "online-support",
  "সাপোর্ট": "online-support",
  "লাইভ ব্যবহার": "data-transfer",
  "স্পিড টেস্ট": "increase",
  "মুভি/FTP সার্ভার": "shared-folder",
  "চেঞ্জ/আপডেট": "process",
  "আমার মেসেজ": "comments",

  // POP / Reseller
  "অনলাইন ক্লায়েন্ট": "wi-fi-connected",
  "অফলাইন ক্লায়েন্ট": "wi-fi",
  "মনিটরিং": "internet",
  "ব্যান্ডউইথ": "data-transfer",
  "নতুন ক্লায়েন্ট": "add-user-male",
  "একটিভ ক্লায়েন্ট": "checked",
  "ইনঅ্যাকটিভ ক্লায়েন্ট": "cancel",
  "নতুন টিকেট": "add-folder",
  "রিফ্রেশ": "sync",
  "সিঙ্ক": "sync",
  "ব্যাকআপ": "cloud-sync",
  "ক্লাউড": "cloud",
  "সার্ভার": "server",
  "রাউটার": "router-symbol",
  "ওয়াইফাই": "wi-fi",
  "নেটওয়ার্ক ক্যাবল": "network-cable",
};

export interface IconLookup {
  url?: string;
  title?: string;
  label?: string;
}

/** Resolve to an icons8 name or undefined. */
export function resolveIcons8(input: IconLookup): string | undefined {
  const { url, title, label } = input;
  if (url && ICONS8_BY_URL[url]) return ICONS8_BY_URL[url];
  if (title && ICONS8_BY_TITLE[title]) return ICONS8_BY_TITLE[title];
  if (label && ICONS8_BY_LABEL[label]) return ICONS8_BY_LABEL[label];
  return undefined;
}

/**
 * Resolve an Icons8 name from a URL pathname.
 * Tries exact match, then progressively trims trailing path segments
 * so /dashboard/billing/list/details still resolves to /dashboard/billing/list.
 */
export function resolveByPath(pathname?: string): string | undefined {
  if (!pathname) return undefined;
  const clean = pathname.split("?")[0].split("#")[0].replace(/\/$/, "");
  if (ICONS8_BY_URL[clean]) return ICONS8_BY_URL[clean];
  const parts = clean.split("/").filter(Boolean);
  while (parts.length > 1) {
    parts.pop();
    const candidate = "/" + parts.join("/");
    if (ICONS8_BY_URL[candidate]) return ICONS8_BY_URL[candidate];
  }
  return undefined;
}
