-- Delete existing demo data
DELETE FROM upazilas;
DELETE FROM districts;

-- Insert all 64 districts of Bangladesh
INSERT INTO districts (name, status) VALUES
('Bagerhat', 'active'),
('Bandarban', 'active'),
('Barguna', 'active'),
('Barisal', 'active'),
('Bhola', 'active'),
('Bogura', 'active'),
('Brahmanbaria', 'active'),
('Chandpur', 'active'),
('Chapainawabganj', 'active'),
('Chattogram', 'active'),
('Chuadanga', 'active'),
('Comilla', 'active'),
('Cox''s Bazar', 'active'),
('Dhaka', 'active'),
('Dinajpur', 'active'),
('Faridpur', 'active'),
('Feni', 'active'),
('Gaibandha', 'active'),
('Gazipur', 'active'),
('Gopalganj', 'active'),
('Habiganj', 'active'),
('Jamalpur', 'active'),
('Jashore', 'active'),
('Jhalakathi', 'active'),
('Jhenaidah', 'active'),
('Joypurhat', 'active'),
('Khagrachhari', 'active'),
('Khulna', 'active'),
('Kishoreganj', 'active'),
('Kurigram', 'active'),
('Kushtia', 'active'),
('Lakshmipur', 'active'),
('Lalmonirhat', 'active'),
('Madaripur', 'active'),
('Magura', 'active'),
('Manikganj', 'active'),
('Meherpur', 'active'),
('Moulvibazar', 'active'),
('Munshiganj', 'active'),
('Mymensingh', 'active'),
('Naogaon', 'active'),
('Narail', 'active'),
('Narayanganj', 'active'),
('Narsingdi', 'active'),
('Natore', 'active'),
('Netrokona', 'active'),
('Nilphamari', 'active'),
('Noakhali', 'active'),
('Pabna', 'active'),
('Panchagarh', 'active'),
('Patuakhali', 'active'),
('Pirojpur', 'active'),
('Rajbari', 'active'),
('Rajshahi', 'active'),
('Rangamati', 'active'),
('Rangpur', 'active'),
('Satkhira', 'active'),
('Shariatpur', 'active'),
('Sherpur', 'active'),
('Sirajganj', 'active'),
('Sunamganj', 'active'),
('Sylhet', 'active'),
('Tangail', 'active'),
('Thakurgaon', 'active');

-- Insert all 622 upazilas with Bangla names and English codes
INSERT INTO upazilas (name, code, district_id, status) VALUES
('অভয়নগর', 'Abhaynagar', (SELECT id FROM districts WHERE name = 'Jashore' LIMIT 1), 'active'),
('আদাবর', 'Adabor', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('আদমদিঘি', 'Adamdighi', (SELECT id FROM districts WHERE name = 'Bogura' LIMIT 1), 'active'),
('আদিতমারী', 'Aditmari', (SELECT id FROM districts WHERE name = 'Lalmonirhat' LIMIT 1), 'active'),
('আগৈলঝাড়া', 'Agailjhara', (SELECT id FROM districts WHERE name = 'Barisal' LIMIT 1), 'active'),
('বিমানবন্দর', 'Airport', (SELECT id FROM districts WHERE name = 'Barisal' LIMIT 1), 'active'),
('বিমানবন্দর', 'Airport', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('বিমানবন্দর (সিলেট)', 'Airport (Sylhet)', (SELECT id FROM districts WHERE name = 'Sylhet' LIMIT 1), 'active'),
('আজমিরীগঞ্জ', 'Ajmiriganj', (SELECT id FROM districts WHERE name = 'Habiganj' LIMIT 1), 'active'),
('আকবর শাহ', 'Akbar Shah', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('আখাউড়া', 'Akhaura', (SELECT id FROM districts WHERE name = 'Brahmanbaria' LIMIT 1), 'active'),
('আক্কেলপুর', 'Akkelpur', (SELECT id FROM districts WHERE name = 'Joypurhat' LIMIT 1), 'active'),
('আলমডাঙ্গা', 'Alamdanga', (SELECT id FROM districts WHERE name = 'Chuadanga' LIMIT 1), 'active'),
('আলফাডাঙ্গা', 'Alfadanga', (SELECT id FROM districts WHERE name = 'Faridpur' LIMIT 1), 'active'),
('আলীকদম', 'Alikadam', (SELECT id FROM districts WHERE name = 'Bandarban' LIMIT 1), 'active'),
('আমিনপুর', 'Aminpur', (SELECT id FROM districts WHERE name = 'Pabna' LIMIT 1), 'active'),
('আমতলী', 'Amtali', (SELECT id FROM districts WHERE name = 'Barguna' LIMIT 1), 'active'),
('আনোয়ারা', 'Anwara', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('আড়াইহাজার', 'Araihazar', (SELECT id FROM districts WHERE name = 'Narayanganj' LIMIT 1), 'active'),
('আড়ংঘাটা', 'Aranghata', (SELECT id FROM districts WHERE name = 'Khulna' LIMIT 1), 'active'),
('আশুগঞ্জ', 'Ashuganj', (SELECT id FROM districts WHERE name = 'Brahmanbaria' LIMIT 1), 'active'),
('আশুলিয়া', 'Ashulia', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('আশাশুনি', 'Assasuni', (SELECT id FROM districts WHERE name = 'Satkhira' LIMIT 1), 'active'),
('আতাইকুলা', 'Ataikula', (SELECT id FROM districts WHERE name = 'Pabna' LIMIT 1), 'active'),
('আটঘরিয়া', 'Atghoria', (SELECT id FROM districts WHERE name = 'Pabna' LIMIT 1), 'active'),
('আটপাড়া', 'Atpara', (SELECT id FROM districts WHERE name = 'Netrokona' LIMIT 1), 'active'),
('আত্রাই', 'Atrai', (SELECT id FROM districts WHERE name = 'Naogaon' LIMIT 1), 'active'),
('আটোয়ারী', 'Atwari', (SELECT id FROM districts WHERE name = 'Panchagarh' LIMIT 1), 'active'),
('অষ্টগ্রাম', 'Austagram', (SELECT id FROM districts WHERE name = 'Kishoreganj' LIMIT 1), 'active'),
('বাবুগঞ্জ', 'Babuganj', (SELECT id FROM districts WHERE name = 'Barisal' LIMIT 1), 'active'),
('বদলগাছী', 'Badalgachi', (SELECT id FROM districts WHERE name = 'Naogaon' LIMIT 1), 'active'),
('বদরগঞ্জ', 'Badargonj', (SELECT id FROM districts WHERE name = 'Rangpur' LIMIT 1), 'active'),
('বাড্ডা', 'Badda', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('বাগাতিপাড়া', 'Bagatipara', (SELECT id FROM districts WHERE name = 'Natore' LIMIT 1), 'active'),
('বাগেরহাট সদর', 'Bagerhat Sadar', (SELECT id FROM districts WHERE name = 'Bagerhat' LIMIT 1), 'active'),
('বাঘা', 'Bagha', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('বাঘাইছড়ি', 'Baghaichari', (SELECT id FROM districts WHERE name = 'Rangamati' LIMIT 1), 'active'),
('বাঘারপাড়া', 'Bagherpara', (SELECT id FROM districts WHERE name = 'Jashore' LIMIT 1), 'active'),
('বাগমারা', 'Bagmara', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('বাহুবল', 'Bahubal', (SELECT id FROM districts WHERE name = 'Habiganj' LIMIT 1), 'active'),
('বাজিতপুর', 'Bajitpur', (SELECT id FROM districts WHERE name = 'Kishoreganj' LIMIT 1), 'active'),
('বাকালিয়া', 'Bakalia', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('বাকেরগঞ্জ', 'Bakerganj', (SELECT id FROM districts WHERE name = 'Barisal' LIMIT 1), 'active'),
('বালাগঞ্জ', 'Balaganj', (SELECT id FROM districts WHERE name = 'Sylhet' LIMIT 1), 'active'),
('বালিয়াডাঙ্গী', 'Baliadangi', (SELECT id FROM districts WHERE name = 'Thakurgaon' LIMIT 1), 'active'),
('বালিয়াকান্দি', 'Baliakandi', (SELECT id FROM districts WHERE name = 'Rajbari' LIMIT 1), 'active'),
('বামনা', 'Bamna', (SELECT id FROM districts WHERE name = 'Barguna' LIMIT 1), 'active'),
('বনানী', 'Banani', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('বানারীপাড়া', 'Banaripara', (SELECT id FROM districts WHERE name = 'Barisal' LIMIT 1), 'active'),
('বাঞ্ছারামপুর', 'Bancharampur', (SELECT id FROM districts WHERE name = 'Brahmanbaria' LIMIT 1), 'active'),
('বন্দর', 'Bandar', (SELECT id FROM districts WHERE name = 'Barisal' LIMIT 1), 'active'),
('বন্দর', 'Bandar', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('বন্দর', 'Bandar', (SELECT id FROM districts WHERE name = 'Narayanganj' LIMIT 1), 'active'),
('বান্দরবান সদর', 'Bandarban Sadar', (SELECT id FROM districts WHERE name = 'Bandarban' LIMIT 1), 'active'),
('বাঙ্গারা বাজার', 'Bangara Bazar', (SELECT id FROM districts WHERE name = 'Comilla' LIMIT 1), 'active'),
('বংশাল', 'Bangshal', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('বানিয়াচং', 'Baniachong', (SELECT id FROM districts WHERE name = 'Habiganj' LIMIT 1), 'active'),
('বাঁশখালী', 'Banshkhali', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('বড়াইগ্রাম', 'Baraigram', (SELECT id FROM districts WHERE name = 'Natore' LIMIT 1), 'active'),
('বরগুনা সদর', 'Barguna Sadar', (SELECT id FROM districts WHERE name = 'Barguna' LIMIT 1), 'active'),
('বারহাট্টা', 'Barhatta', (SELECT id FROM districts WHERE name = 'Netrokona' LIMIT 1), 'active'),
('বরিশাল সদর', 'Barisal Sadar', (SELECT id FROM districts WHERE name = 'Barisal' LIMIT 1), 'active'),
('বরকল', 'Barkal', (SELECT id FROM districts WHERE name = 'Rangamati' LIMIT 1), 'active'),
('বড়লেখা', 'Barlekha', (SELECT id FROM districts WHERE name = 'Moulvibazar' LIMIT 1), 'active'),
('বরুড়া', 'Barura', (SELECT id FROM districts WHERE name = 'Comilla' LIMIT 1), 'active'),
('বাসাইল', 'Basail', (SELECT id FROM districts WHERE name = 'Tangail' LIMIT 1), 'active'),
('বাসন', 'Bason', (SELECT id FROM districts WHERE name = 'Gazipur' LIMIT 1), 'active'),
('বাউফল', 'Bauphal', (SELECT id FROM districts WHERE name = 'Patuakhali' LIMIT 1), 'active'),
('বায়েজিদ বোস্তামী', 'Bayejid Bostami', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('বঙ্গবন্ধু সেতু (পূর্ব)', 'BB. Bridge (East)', (SELECT id FROM districts WHERE name = 'Tangail' LIMIT 1), 'active'),
('বঙ্গবন্ধু সেতু (পশ্চিম)', 'BB. Bridge (West)', (SELECT id FROM districts WHERE name = 'Sirajganj' LIMIT 1), 'active'),
('বিয়ানীবাজার', 'Beanibazar', (SELECT id FROM districts WHERE name = 'Sylhet' LIMIT 1), 'active'),
('বেগমগঞ্জ', 'Begumganj', (SELECT id FROM districts WHERE name = 'Noakhali' LIMIT 1), 'active'),
('বেলাবো', 'Belabo', (SELECT id FROM districts WHERE name = 'Narsingdi' LIMIT 1), 'active'),
('বিলাইছড়ি', 'Belaichari', (SELECT id FROM districts WHERE name = 'Rangamati' LIMIT 1), 'active'),
('বেলকুচি', 'Belkuchi', (SELECT id FROM districts WHERE name = 'Sirajganj' LIMIT 1), 'active'),
('বেলপুকুর', 'Belpukur', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('বেনাপোল পোর্ট', 'Benapole Port', (SELECT id FROM districts WHERE name = 'Jashore' LIMIT 1), 'active'),
('বেড়া', 'Bera', (SELECT id FROM districts WHERE name = 'Pabna' LIMIT 1), 'active'),
('বেতাগী', 'Betagi', (SELECT id FROM districts WHERE name = 'Barguna' LIMIT 1), 'active'),
('ভৈরব', 'Bhairab', (SELECT id FROM districts WHERE name = 'Kishoreganj' LIMIT 1), 'active'),
('ভালুকা', 'Bhaluka', (SELECT id FROM districts WHERE name = 'Mymensingh' LIMIT 1), 'active'),
('ভান্ডারিয়া', 'Bhandaria', (SELECT id FROM districts WHERE name = 'Pirojpur' LIMIT 1), 'active'),
('ভাঙ্গা', 'Bhanga', (SELECT id FROM districts WHERE name = 'Faridpur' LIMIT 1), 'active'),
('ভাঙ্গুড়া', 'Bhangura', (SELECT id FROM districts WHERE name = 'Pabna' LIMIT 1), 'active'),
('ভাসান টেক', 'Bhasan Tek', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('ভাটারা', 'Bhatara', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('ভেদরগঞ্জ', 'Bhedarganj', (SELECT id FROM districts WHERE name = 'Shariatpur' LIMIT 1), 'active'),
('ভেড়ামারা', 'Bheramara', (SELECT id FROM districts WHERE name = 'Kushtia' LIMIT 1), 'active'),
('ভোলা সদর', 'Bhola Sadar', (SELECT id FROM districts WHERE name = 'Bhola' LIMIT 1), 'active'),
('ভোলাহাট', 'Bholahat', (SELECT id FROM districts WHERE name = 'Chapainawabganj' LIMIT 1), 'active'),
('ভুয়াপুর', 'Bhuapur', (SELECT id FROM districts WHERE name = 'Tangail' LIMIT 1), 'active'),
('ভুরুঙ্গামারী', 'Bhurungamari', (SELECT id FROM districts WHERE name = 'Kurigram' LIMIT 1), 'active'),
('বিজয়নগর', 'Bijoynagar', (SELECT id FROM districts WHERE name = 'Brahmanbaria' LIMIT 1), 'active'),
('বিমান বন্দর', 'Biman Bandar', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('বিরামপুর', 'Birampur', (SELECT id FROM districts WHERE name = 'Dinajpur' LIMIT 1), 'active'),
('বীরগঞ্জ', 'Birganj', (SELECT id FROM districts WHERE name = 'Dinajpur' LIMIT 1), 'active'),
('বিরল', 'Birol', (SELECT id FROM districts WHERE name = 'Dinajpur' LIMIT 1), 'active'),
('বিশ্বম্ভরপুর', 'Bishwambarpur', (SELECT id FROM districts WHERE name = 'Sunamganj' LIMIT 1), 'active'),
('বিশ্বনাথ', 'Bishwanath', (SELECT id FROM districts WHERE name = 'Sylhet' LIMIT 1), 'active'),
('বোয়ালিয়া', 'Boalia', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('বোয়ালখালী', 'Boalkhali', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('বোয়ালমারী', 'Boalmari', (SELECT id FROM districts WHERE name = 'Faridpur' LIMIT 1), 'active'),
('বোচাগঞ্জ', 'Bochaganj', (SELECT id FROM districts WHERE name = 'Dinajpur' LIMIT 1), 'active'),
('বোদা', 'Boda', (SELECT id FROM districts WHERE name = 'Panchagarh' LIMIT 1), 'active'),
('বগুড়া সদর', 'Bogra Sadar', (SELECT id FROM districts WHERE name = 'Bogura' LIMIT 1), 'active'),
('বকশীগঞ্জ', 'Bokshiganj', (SELECT id FROM districts WHERE name = 'Jamalpur' LIMIT 1), 'active'),
('বোরহান উদ্দিন', 'Borhan Uddin', (SELECT id FROM districts WHERE name = 'Bhola' LIMIT 1), 'active'),
('বটিয়াঘাটা', 'Botiaghata', (SELECT id FROM districts WHERE name = 'Khulna' LIMIT 1), 'active'),
('ব্রাহ্মণবাড়িয়া সদর', 'Brahmanbaria Sadar', (SELECT id FROM districts WHERE name = 'Brahmanbaria' LIMIT 1), 'active'),
('ব্রাহ্মণপাড়া', 'Brahmanpara', (SELECT id FROM districts WHERE name = 'Comilla' LIMIT 1), 'active'),
('বুড়িচং', 'Burichang', (SELECT id FROM districts WHERE name = 'Comilla' LIMIT 1), 'active'),
('সেনানিবাস', 'Cantonment', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('চক বাজার', 'Chak Bazar', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('চকরিয়া', 'Chakaria', (SELECT id FROM districts WHERE name = 'Cox''s Bazar' LIMIT 1), 'active'),
('চন্দনাইশ', 'Chandanaish', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('চান্দগাঁও', 'Chandgaon', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('চান্দিনা', 'Chandina', (SELECT id FROM districts WHERE name = 'Comilla' LIMIT 1), 'active'),
('চাঁদপুর সদর', 'Chandpur Sadar', (SELECT id FROM districts WHERE name = 'Chandpur' LIMIT 1), 'active'),
('চদ্রিমা', 'Chandrima', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('চন্দ্রঘোনা', 'Chandroghona', (SELECT id FROM districts WHERE name = 'Rangamati' LIMIT 1), 'active'),
('চাঁপাইনবাবগঞ্জ সদর', 'Chapainawabganj Sadar', (SELECT id FROM districts WHERE name = 'Chapainawabganj' LIMIT 1), 'active'),
('চরমোনাই', 'Char Monai', (SELECT id FROM districts WHERE name = 'Barisal' LIMIT 1), 'active'),
('চরভদ্রাসন', 'Charbhadrasan', (SELECT id FROM districts WHERE name = 'Faridpur' LIMIT 1), 'active'),
('চরফ্যাশন', 'Charfesson', (SELECT id FROM districts WHERE name = 'Bhola' LIMIT 1), 'active'),
('চারঘাট', 'Charghat', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('চর রাজিবপুর', 'Charrajibpur', (SELECT id FROM districts WHERE name = 'Kurigram' LIMIT 1), 'active'),
('চাষাঢ়', 'Chashar', (SELECT id FROM districts WHERE name = 'Madaripur' LIMIT 1), 'active'),
('চাটখিল', 'Chatkhil', (SELECT id FROM districts WHERE name = 'Noakhali' LIMIT 1), 'active'),
('চাটমোহর', 'Chatmohar', (SELECT id FROM districts WHERE name = 'Pabna' LIMIT 1), 'active'),
('চৌদ্দগ্রাম', 'Chauddagram', (SELECT id FROM districts WHERE name = 'Comilla' LIMIT 1), 'active'),
('চৌহালি', 'Chauhali', (SELECT id FROM districts WHERE name = 'Sirajganj' LIMIT 1), 'active'),
('চক বাজার', 'Chawk Bazar', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('ছাগলনাইয়া', 'Chhagalnaiya', (SELECT id FROM districts WHERE name = 'Feni' LIMIT 1), 'active'),
('ছাতক', 'Chhatak', (SELECT id FROM districts WHERE name = 'Sunamganj' LIMIT 1), 'active'),
('চিলমারী', 'Chilmari', (SELECT id FROM districts WHERE name = 'Kurigram' LIMIT 1), 'active'),
('চিরিরবন্দর', 'Chirirbandar', (SELECT id FROM districts WHERE name = 'Dinajpur' LIMIT 1), 'active'),
('চিতলমারী', 'Chitalmari', (SELECT id FROM districts WHERE name = 'Bagerhat' LIMIT 1), 'active'),
('চট্টগ্রাম কোতোয়ালি', 'Chittagong Kotwali', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('চৌগাছা', 'Chougachha', (SELECT id FROM districts WHERE name = 'Jashore' LIMIT 1), 'active'),
('চুয়াডাঙ্গা সদর', 'Chuadanga Sadar', (SELECT id FROM districts WHERE name = 'Chuadanga' LIMIT 1), 'active'),
('চুনারুঘাট', 'Chunarughat', (SELECT id FROM districts WHERE name = 'Habiganj' LIMIT 1), 'active'),
('কুমিল্লা সদর', 'Comilla Sadar', (SELECT id FROM districts WHERE name = 'Comilla' LIMIT 1), 'active'),
('কোম্পানীগঞ্জ', 'Companiganj', (SELECT id FROM districts WHERE name = 'Noakhali' LIMIT 1), 'active'),
('কোম্পানীগঞ্জ', 'Companiganj', (SELECT id FROM districts WHERE name = 'Sylhet' LIMIT 1), 'active'),
('কক্সবাজার সদর', 'Coxsbazar Sadar', (SELECT id FROM districts WHERE name = 'Cox''s Bazar' LIMIT 1), 'active'),
('দাগনভূঞা', 'Daganbhuiyan', (SELECT id FROM districts WHERE name = 'Feni' LIMIT 1), 'active'),
('দাকোপ', 'Dakop', (SELECT id FROM districts WHERE name = 'Khulna' LIMIT 1), 'active'),
('দক্ষিণখান', 'Dakshinkhan', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('দামুড়হুদা', 'Damurhuda', (SELECT id FROM districts WHERE name = 'Chuadanga' LIMIT 1), 'active'),
('দশমিনা', 'Dashmina', (SELECT id FROM districts WHERE name = 'Patuakhali' LIMIT 1), 'active'),
('দাউদকান্দি', 'Daudkandi', (SELECT id FROM districts WHERE name = 'Comilla' LIMIT 1), 'active'),
('দাউলতকান', 'Daulatkhan', (SELECT id FROM districts WHERE name = 'Bhola' LIMIT 1), 'active'),
('দাউলতপুর', 'Daulatpur', (SELECT id FROM districts WHERE name = 'Khulna' LIMIT 1), 'active'),
('দেবহাটা', 'Debhata', (SELECT id FROM districts WHERE name = 'Satkhira' LIMIT 1), 'active'),
('দেবিদ্বার', 'Debidwar', (SELECT id FROM districts WHERE name = 'Comilla' LIMIT 1), 'active'),
('দেলদুয়ার', 'Delduar', (SELECT id FROM districts WHERE name = 'Tangail' LIMIT 1), 'active'),
('দেওয়ানগঞ্জ', 'Dewanganj', (SELECT id FROM districts WHERE name = 'Jamalpur' LIMIT 1), 'active'),
('ধামরাই', 'Dhamrai', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('ধানমন্ডি', 'Dhanmondi', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('ধনবাড়ী', 'Dhanbari', (SELECT id FROM districts WHERE name = 'Tangail' LIMIT 1), 'active'),
('ধর্মপাশা', 'Dharmapasha', (SELECT id FROM districts WHERE name = 'Sunamganj' LIMIT 1), 'active'),
('ধুনট', 'Dhunat', (SELECT id FROM districts WHERE name = 'Bogura' LIMIT 1), 'active'),
('ধুনচি', 'Dhunchi', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('ধুপচাঁচিয়া', 'Dhupchachiya', (SELECT id FROM districts WHERE name = 'Bogura' LIMIT 1), 'active'),
('দিঘিনালা', 'Dighinala', (SELECT id FROM districts WHERE name = 'Khagrachhari' LIMIT 1), 'active'),
('দিনাজপুর সদর', 'Dinajpur Sadar', (SELECT id FROM districts WHERE name = 'Dinajpur' LIMIT 1), 'active'),
('দোহার', 'Dohar', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('ডোমার', 'Domar', (SELECT id FROM districts WHERE name = 'Nilphamari' LIMIT 1), 'active'),
('ডবল মুরিং', 'Double Mooring', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('দুবলার চর', 'Dublar Char', (SELECT id FROM districts WHERE name = 'Bagerhat' LIMIT 1), 'active'),
('দুদপুকুরিয়া', 'Dudpukuria', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('দুলালবাজার', 'Dulalbazar', (SELECT id FROM districts WHERE name = 'Sunamganj' LIMIT 1), 'active'),
('ডুমুরিয়া', 'Dumuria', (SELECT id FROM districts WHERE name = 'Khulna' LIMIT 1), 'active'),
('দুর্গাপুর', 'Durgapur', (SELECT id FROM districts WHERE name = 'Netrokona' LIMIT 1), 'active'),
('দুর্গাপুর', 'Durgapur', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('ফরিদগঞ্জ', 'Faridganj', (SELECT id FROM districts WHERE name = 'Chandpur' LIMIT 1), 'active'),
('ফরিদপুর সদর', 'Faridpur Sadar', (SELECT id FROM districts WHERE name = 'Faridpur' LIMIT 1), 'active'),
('ফটিকছড়ি', 'Fatikchhari', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('ফেনী সদর', 'Feni Sadar', (SELECT id FROM districts WHERE name = 'Feni' LIMIT 1), 'active'),
('ফুলবাড়ী', 'Fulbari', (SELECT id FROM districts WHERE name = 'Kurigram' LIMIT 1), 'active'),
('ফুলবাড়ী', 'Fulbari', (SELECT id FROM districts WHERE name = 'Dinajpur' LIMIT 1), 'active'),
('ফুলগাজী', 'Fulgazi', (SELECT id FROM districts WHERE name = 'Feni' LIMIT 1), 'active'),
('ফুলপুর', 'Fulpur', (SELECT id FROM districts WHERE name = 'Mymensingh' LIMIT 1), 'active'),
('গাবতলী', 'Gabtali', (SELECT id FROM districts WHERE name = 'Bogura' LIMIT 1), 'active'),
('গাফরগাঁও', 'Gafargaon', (SELECT id FROM districts WHERE name = 'Mymensingh' LIMIT 1), 'active'),
('গাইবান্ধা সদর', 'Gaibandha Sadar', (SELECT id FROM districts WHERE name = 'Gaibandha' LIMIT 1), 'active'),
('গৈয়াবান্ধা', 'Gaiybandha', (SELECT id FROM districts WHERE name = 'Gaibandha' LIMIT 1), 'active'),
('গালাচিপা', 'Galachipa', (SELECT id FROM districts WHERE name = 'Patuakhali' LIMIT 1), 'active'),
('গাংনী', 'Gangni', (SELECT id FROM districts WHERE name = 'Meherpur' LIMIT 1), 'active'),
('গাজীপুর সদর', 'Gazipur Sadar', (SELECT id FROM districts WHERE name = 'Gazipur' LIMIT 1), 'active'),
('ঘাটাইল', 'Ghatail', (SELECT id FROM districts WHERE name = 'Tangail' LIMIT 1), 'active'),
('ঘিওর', 'Ghior', (SELECT id FROM districts WHERE name = 'Manikganj' LIMIT 1), 'active'),
('গোবিন্দগঞ্জ', 'Gobindaganj', (SELECT id FROM districts WHERE name = 'Gaibandha' LIMIT 1), 'active'),
('গোদাগাড়ী', 'Godagari', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('গোপালগঞ্জ সদর', 'Gopalganj Sadar', (SELECT id FROM districts WHERE name = 'Gopalganj' LIMIT 1), 'active'),
('গোপালপুর', 'Gopalpur', (SELECT id FROM districts WHERE name = 'Tangail' LIMIT 1), 'active'),
('গোসাইরহাট', 'Gosairhat', (SELECT id FROM districts WHERE name = 'Shariatpur' LIMIT 1), 'active'),
('গোয়াইনঘাট', 'Gowainghat', (SELECT id FROM districts WHERE name = 'Sylhet' LIMIT 1), 'active'),
('গুইমারা', 'Guimara', (SELECT id FROM districts WHERE name = 'Khagrachhari' LIMIT 1), 'active'),
('গুলশান', 'Gulshan', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('গুরুদাসপুর', 'Gurudaspur', (SELECT id FROM districts WHERE name = 'Natore' LIMIT 1), 'active'),
('গাউরনদী', 'Gournadi', (SELECT id FROM districts WHERE name = 'Barisal' LIMIT 1), 'active'),
('হবিগঞ্জ সদর', 'Habiganj Sadar', (SELECT id FROM districts WHERE name = 'Habiganj' LIMIT 1), 'active'),
('হাইমচর', 'Haimchar', (SELECT id FROM districts WHERE name = 'Chandpur' LIMIT 1), 'active'),
('হাজীগঞ্জ', 'Hajiganj', (SELECT id FROM districts WHERE name = 'Chandpur' LIMIT 1), 'active'),
('হালিশহর', 'Halishahar', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('হরিণাকুন্ডু', 'Harinakunda', (SELECT id FROM districts WHERE name = 'Jhenaidah' LIMIT 1), 'active'),
('হারিরামপুর', 'Harirampur', (SELECT id FROM districts WHERE name = 'Manikganj' LIMIT 1), 'active'),
('হাতহাজারী', 'Hathazari', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('হাতীবান্ধা', 'Hatibandha', (SELECT id FROM districts WHERE name = 'Lalmonirhat' LIMIT 1), 'active'),
('হাটশিরা', 'Hatshira', (SELECT id FROM districts WHERE name = 'Khulna' LIMIT 1), 'active'),
('হিজলা', 'Hijla', (SELECT id FROM districts WHERE name = 'Barisal' LIMIT 1), 'active'),
('হোসেনপুর', 'Hossenpur', (SELECT id FROM districts WHERE name = 'Kishoreganj' LIMIT 1), 'active'),
('ইসলামপুর', 'Islampur', (SELECT id FROM districts WHERE name = 'Jamalpur' LIMIT 1), 'active'),
('ঈশ্বরদী', 'Ishwardi', (SELECT id FROM districts WHERE name = 'Pabna' LIMIT 1), 'active'),
('ঈশ্বরগঞ্জ', 'Ishwarganj', (SELECT id FROM districts WHERE name = 'Mymensingh' LIMIT 1), 'active'),
('ইটনা', 'Itna', (SELECT id FROM districts WHERE name = 'Kishoreganj' LIMIT 1), 'active'),
('জগন্নাথপুর', 'Jagannathpur', (SELECT id FROM districts WHERE name = 'Sunamganj' LIMIT 1), 'active'),
('জৈন্তাপুর', 'Jaintapur', (SELECT id FROM districts WHERE name = 'Sylhet' LIMIT 1), 'active'),
('জালঢাকা', 'Jaldhaka', (SELECT id FROM districts WHERE name = 'Nilphamari' LIMIT 1), 'active'),
('জামালগঞ্জ', 'Jamalganj', (SELECT id FROM districts WHERE name = 'Sunamganj' LIMIT 1), 'active'),
('জামালপুর সদর', 'Jamalpur Sadar', (SELECT id FROM districts WHERE name = 'Jamalpur' LIMIT 1), 'active'),
('যশোর সদর', 'Jashore Sadar', (SELECT id FROM districts WHERE name = 'Jashore' LIMIT 1), 'active'),
('ঝালকাঠি সদর', 'Jhalakathi Sadar', (SELECT id FROM districts WHERE name = 'Jhalakathi' LIMIT 1), 'active'),
('ঝিকরগাছা', 'Jhikargacha', (SELECT id FROM districts WHERE name = 'Jashore' LIMIT 1), 'active'),
('ঝিনাইদহ সদর', 'Jhenaidah Sadar', (SELECT id FROM districts WHERE name = 'Jhenaidah' LIMIT 1), 'active'),
('জয়পুরহাট সদর', 'Joypurhat Sadar', (SELECT id FROM districts WHERE name = 'Joypurhat' LIMIT 1), 'active'),
('জুড়ী', 'Juri', (SELECT id FROM districts WHERE name = 'Moulvibazar' LIMIT 1), 'active'),
('কাদামতলী', 'Kadamtali', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('কালের পোল', 'Kaler Pool', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('কালিয়া', 'Kalia', (SELECT id FROM districts WHERE name = 'Narail' LIMIT 1), 'active'),
('কালিয়াকৈর', 'Kaliakair', (SELECT id FROM districts WHERE name = 'Gazipur' LIMIT 1), 'active'),
('কালিগঞ্জ', 'Kaliganj', (SELECT id FROM districts WHERE name = 'Jhenaidah' LIMIT 1), 'active'),
('কালিগঞ্জ', 'Kaliganj', (SELECT id FROM districts WHERE name = 'Satkhira' LIMIT 1), 'active'),
('কালীহাতী', 'Kalihati', (SELECT id FROM districts WHERE name = 'Tangail' LIMIT 1), 'active'),
('কালকিনি', 'Kalkini', (SELECT id FROM districts WHERE name = 'Madaripur' LIMIT 1), 'active'),
('কালমাকান্দা', 'Kalmakanda', (SELECT id FROM districts WHERE name = 'Netrokona' LIMIT 1), 'active'),
('কামালগঞ্জ', 'Kamalganj', (SELECT id FROM districts WHERE name = 'Moulvibazar' LIMIT 1), 'active'),
('কামরাঙ্গীরচর', 'Kamrangirchar', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('কানাইঘাট', 'Kanaighat', (SELECT id FROM districts WHERE name = 'Sylhet' LIMIT 1), 'active'),
('কাপাসিয়া', 'Kapasia', (SELECT id FROM districts WHERE name = 'Gazipur' LIMIT 1), 'active'),
('কাপ্তাই', 'Kaptai', (SELECT id FROM districts WHERE name = 'Rangamati' LIMIT 1), 'active'),
('কর্ণফুলী', 'Karnafuli', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('কসবা', 'Kasba', (SELECT id FROM districts WHERE name = 'Brahmanbaria' LIMIT 1), 'active'),
('কাশিয়ানী', 'Kashiani', (SELECT id FROM districts WHERE name = 'Gopalganj' LIMIT 1), 'active'),
('কাটালিয়া', 'Katalia', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('কাউখালী', 'Kaukhali', (SELECT id FROM districts WHERE name = 'Pirojpur' LIMIT 1), 'active'),
('কাউখালী', 'Kaukhali', (SELECT id FROM districts WHERE name = 'Rangamati' LIMIT 1), 'active'),
('কাওরাইদ', 'Kawraid', (SELECT id FROM districts WHERE name = 'Sirajganj' LIMIT 1), 'active'),
('কেন্দুয়া', 'Kendua', (SELECT id FROM districts WHERE name = 'Netrokona' LIMIT 1), 'active'),
('কেরানীগঞ্জ', 'Keraniganj', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('খাগড়াছড়ি সদর', 'Khagrachhari Sadar', (SELECT id FROM districts WHERE name = 'Khagrachhari' LIMIT 1), 'active'),
('খালিশপুর', 'Khalishpur', (SELECT id FROM districts WHERE name = 'Khulna' LIMIT 1), 'active'),
('খানসামা', 'Khansama', (SELECT id FROM districts WHERE name = 'Dinajpur' LIMIT 1), 'active'),
('খিলগাঁও', 'Khilgaon', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('খিলক্ষেত', 'Khilkhet', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('খোকসা', 'Khoksa', (SELECT id FROM districts WHERE name = 'Kushtia' LIMIT 1), 'active'),
('খুলনা সদর', 'Khulna Sadar', (SELECT id FROM districts WHERE name = 'Khulna' LIMIT 1), 'active'),
('কিশোরগঞ্জ সদর', 'Kishoreganj Sadar', (SELECT id FROM districts WHERE name = 'Kishoreganj' LIMIT 1), 'active'),
('কোটালীপাড়া', 'Kotalipara', (SELECT id FROM districts WHERE name = 'Gopalganj' LIMIT 1), 'active'),
('কোতোয়ালি', 'Kotwali', (SELECT id FROM districts WHERE name = 'Comilla' LIMIT 1), 'active'),
('কোতোয়ালি', 'Kotwali', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('কুলাউড়া', 'Kulaura', (SELECT id FROM districts WHERE name = 'Moulvibazar' LIMIT 1), 'active'),
('কুমারখালী', 'Kumarkhali', (SELECT id FROM districts WHERE name = 'Kushtia' LIMIT 1), 'active'),
('কুড়িগ্রাম সদর', 'Kurigram Sadar', (SELECT id FROM districts WHERE name = 'Kurigram' LIMIT 1), 'active'),
('কুষ্টিয়া সদর', 'Kushtia Sadar', (SELECT id FROM districts WHERE name = 'Kushtia' LIMIT 1), 'active'),
('লাখাই', 'Lakhai', (SELECT id FROM districts WHERE name = 'Habiganj' LIMIT 1), 'active'),
('লক্ষীপুর সদর', 'Lakshmipur Sadar', (SELECT id FROM districts WHERE name = 'Lakshmipur' LIMIT 1), 'active'),
('লক্ষ্মীছড়ি', 'Lakshmichhari', (SELECT id FROM districts WHERE name = 'Khagrachhari' LIMIT 1), 'active'),
('লালবাগ', 'Lalbag', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('লালমনিরহাট সদর', 'Lalmonirhat Sadar', (SELECT id FROM districts WHERE name = 'Lalmonirhat' LIMIT 1), 'active'),
('লালমোহন', 'Lalmohan', (SELECT id FROM districts WHERE name = 'Bhola' LIMIT 1), 'active'),
('লালপুর', 'Lalpur', (SELECT id FROM districts WHERE name = 'Natore' LIMIT 1), 'active'),
('লামা', 'Lama', (SELECT id FROM districts WHERE name = 'Bandarban' LIMIT 1), 'active'),
('লাঙ্গলকোট', 'Langalkot', (SELECT id FROM districts WHERE name = 'Comilla' LIMIT 1), 'active'),
('লোহাগাড়া', 'Lohagara', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('লোহাগাড়া', 'Lohagara', (SELECT id FROM districts WHERE name = 'Narail' LIMIT 1), 'active'),
('লোহাগড়া', 'Lohagora', (SELECT id FROM districts WHERE name = 'Narail' LIMIT 1), 'active'),
('লংদু', 'Longdu', (SELECT id FROM districts WHERE name = 'Rangamati' LIMIT 1), 'active'),
('মাদারগঞ্জ', 'Madarganj', (SELECT id FROM districts WHERE name = 'Jamalpur' LIMIT 1), 'active'),
('মাদারীপুর সদর', 'Madaripur Sadar', (SELECT id FROM districts WHERE name = 'Madaripur' LIMIT 1), 'active'),
('মধুখালী', 'Madhukhali', (SELECT id FROM districts WHERE name = 'Faridpur' LIMIT 1), 'active'),
('মধ্যনগর', 'Madhyanagar', (SELECT id FROM districts WHERE name = 'Sunamganj' LIMIT 1), 'active'),
('মাগুরা সদর', 'Magura Sadar', (SELECT id FROM districts WHERE name = 'Magura' LIMIT 1), 'active'),
('মহাদেবপুর', 'Mahadebpur', (SELECT id FROM districts WHERE name = 'Naogaon' LIMIT 1), 'active'),
('মহাখালী', 'Mohakhali', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('মহালছড়ি', 'Mahalchhari', (SELECT id FROM districts WHERE name = 'Khagrachhari' LIMIT 1), 'active'),
('মহাম্মদপুর', 'Mohammadpur', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('মহাম্মদপুর', 'Mohammadpur', (SELECT id FROM districts WHERE name = 'Magura' LIMIT 1), 'active'),
('মহেশখালী', 'Maheshkhali', (SELECT id FROM districts WHERE name = 'Cox''s Bazar' LIMIT 1), 'active'),
('মহেশপুর', 'Maheshpur', (SELECT id FROM districts WHERE name = 'Jhenaidah' LIMIT 1), 'active'),
('মানিকছড়ি', 'Manikchari', (SELECT id FROM districts WHERE name = 'Khagrachhari' LIMIT 1), 'active'),
('মানিকগঞ্জ সদর', 'Manikganj Sadar', (SELECT id FROM districts WHERE name = 'Manikganj' LIMIT 1), 'active'),
('মনোহরদী', 'Manohardi', (SELECT id FROM districts WHERE name = 'Narsingdi' LIMIT 1), 'active'),
('মনপুরা', 'Monpura', (SELECT id FROM districts WHERE name = 'Bhola' LIMIT 1), 'active'),
('মতিঝিল', 'Motijheel', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('মাতিরাঙ্গা', 'Matiranga', (SELECT id FROM districts WHERE name = 'Khagrachhari' LIMIT 1), 'active'),
('মতলব দক্ষিণ', 'Matlab Dakshin', (SELECT id FROM districts WHERE name = 'Chandpur' LIMIT 1), 'active'),
('মতলব উত্তর', 'Matlab Uttar', (SELECT id FROM districts WHERE name = 'Chandpur' LIMIT 1), 'active'),
('মাওলানা বাজার', 'Maulana Bazar', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('মাওলভীবাজার সদর', 'Maulvibazar Sadar', (SELECT id FROM districts WHERE name = 'Moulvibazar' LIMIT 1), 'active'),
('মেহেরপুর সদর', 'Meherpur Sadar', (SELECT id FROM districts WHERE name = 'Meherpur' LIMIT 1), 'active'),
('মেলান্দহ', 'Melandah', (SELECT id FROM districts WHERE name = 'Jamalpur' LIMIT 1), 'active'),
('মিরপুর', 'Mirpur', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('মিরপুর', 'Mirpur', (SELECT id FROM districts WHERE name = 'Kushtia' LIMIT 1), 'active'),
('মিরসরাই', 'Mirsarai', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('মিঠামইন', 'Mithamoin', (SELECT id FROM districts WHERE name = 'Kishoreganj' LIMIT 1), 'active'),
('মিঠাপুকুর', 'Mithapukur', (SELECT id FROM districts WHERE name = 'Rangpur' LIMIT 1), 'active'),
('মোহনগঞ্জ', 'Mohanganj', (SELECT id FROM districts WHERE name = 'Netrokona' LIMIT 1), 'active'),
('মোহনপুর', 'Mohanpur', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('মোল্লাহাট', 'Mollahat', (SELECT id FROM districts WHERE name = 'Bagerhat' LIMIT 1), 'active'),
('মোংলা', 'Mongla', (SELECT id FROM districts WHERE name = 'Bagerhat' LIMIT 1), 'active'),
('মোরেলগঞ্জ', 'Morolganj', (SELECT id FROM districts WHERE name = 'Bagerhat' LIMIT 1), 'active'),
('মুক্তাগাছা', 'Muktagachha', (SELECT id FROM districts WHERE name = 'Mymensingh' LIMIT 1), 'active'),
('মুন্সীগঞ্জ সদর', 'Munshiganj Sadar', (SELECT id FROM districts WHERE name = 'Munshiganj' LIMIT 1), 'active'),
('মুরাদনগর', 'Muradnagar', (SELECT id FROM districts WHERE name = 'Comilla' LIMIT 1), 'active'),
('মাইমনসিং সদর', 'Mymensingh Sadar', (SELECT id FROM districts WHERE name = 'Mymensingh' LIMIT 1), 'active'),
('নবাবগঞ্জ', 'Nabinagar', (SELECT id FROM districts WHERE name = 'Brahmanbaria' LIMIT 1), 'active'),
('নাচোল', 'Nachole', (SELECT id FROM districts WHERE name = 'Chapainawabganj' LIMIT 1), 'active'),
('নাগরপুর', 'Nagarpur', (SELECT id FROM districts WHERE name = 'Tangail' LIMIT 1), 'active'),
('নাঙ্গলকোট', 'Nangalkot', (SELECT id FROM districts WHERE name = 'Comilla' LIMIT 1), 'active'),
('নওগাঁ সদর', 'Naogaon Sadar', (SELECT id FROM districts WHERE name = 'Naogaon' LIMIT 1), 'active'),
('নড়াইল সদর', 'Narail Sadar', (SELECT id FROM districts WHERE name = 'Narail' LIMIT 1), 'active'),
('নারায়ণগঞ্জ সদর', 'Narayanganj Sadar', (SELECT id FROM districts WHERE name = 'Narayanganj' LIMIT 1), 'active'),
('নরসিংদী সদর', 'Narsingdi Sadar', (SELECT id FROM districts WHERE name = 'Narsingdi' LIMIT 1), 'active'),
('নাসিরনগর', 'Nasirnagar', (SELECT id FROM districts WHERE name = 'Brahmanbaria' LIMIT 1), 'active'),
('নাটোর সদর', 'Natore Sadar', (SELECT id FROM districts WHERE name = 'Natore' LIMIT 1), 'active'),
('নওয়াবগঞ্জ', 'Nawabganj', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('নেছারাবাদ', 'Nesarabad', (SELECT id FROM districts WHERE name = 'Pirojpur' LIMIT 1), 'active'),
('নেত্রকোণা সদর', 'Netrokona Sadar', (SELECT id FROM districts WHERE name = 'Netrokona' LIMIT 1), 'active'),
('নিকলী', 'Nikli', (SELECT id FROM districts WHERE name = 'Kishoreganj' LIMIT 1), 'active'),
('নীলফামারী সদর', 'Nilphamari Sadar', (SELECT id FROM districts WHERE name = 'Nilphamari' LIMIT 1), 'active'),
('নোয়াখালী সদর', 'Noakhali Sadar', (SELECT id FROM districts WHERE name = 'Noakhali' LIMIT 1), 'active'),
('নবাবগঞ্জ (ঢাকা)', 'Nobabganj (Dhaka)', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('পাবনা সদর', 'Pabna Sadar', (SELECT id FROM districts WHERE name = 'Pabna' LIMIT 1), 'active'),
('পাঁচবিবি', 'Pachbibi', (SELECT id FROM districts WHERE name = 'Joypurhat' LIMIT 1), 'active'),
('পাহাড়তলী', 'Pahartali', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('পাইকগাছা', 'Paikgachha', (SELECT id FROM districts WHERE name = 'Khulna' LIMIT 1), 'active'),
('পাকুন্দিয়া', 'Pakundia', (SELECT id FROM districts WHERE name = 'Kishoreganj' LIMIT 1), 'active'),
('পলাশ', 'Palash', (SELECT id FROM districts WHERE name = 'Narsingdi' LIMIT 1), 'active'),
('পল্লবী', 'Pallabi', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('পাংশা', 'Pangsha', (SELECT id FROM districts WHERE name = 'Rajbari' LIMIT 1), 'active'),
('পাঁচখানি', 'Panchkhani', (SELECT id FROM districts WHERE name = 'Panchagarh' LIMIT 1), 'active'),
('পঞ্চগড় সদর', 'Panchagarh Sadar', (SELECT id FROM districts WHERE name = 'Panchagarh' LIMIT 1), 'active'),
('পাঁচলাইশ', 'Panchlaish', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('পরশুরাম', 'Parshuram', (SELECT id FROM districts WHERE name = 'Feni' LIMIT 1), 'active'),
('পটিয়া', 'Patiya', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('পতনঊষার', 'Patnouchar', (SELECT id FROM districts WHERE name = 'Sunamganj' LIMIT 1), 'active'),
('পটুয়াখালী সদর', 'Patuakhali Sadar', (SELECT id FROM districts WHERE name = 'Patuakhali' LIMIT 1), 'active'),
('পবা', 'Pba', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('পীরগঞ্জ', 'Pirganj', (SELECT id FROM districts WHERE name = 'Rangpur' LIMIT 1), 'active'),
('পীরগঞ্জ', 'Pirganj', (SELECT id FROM districts WHERE name = 'Thakurgaon' LIMIT 1), 'active'),
('পিরোজপুর সদর', 'Pirojpur Sadar', (SELECT id FROM districts WHERE name = 'Pirojpur' LIMIT 1), 'active'),
('পূর্বাচল', 'Purbachal', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('পুঠিয়া', 'Puthia', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('রাইপুরা', 'Raipura', (SELECT id FROM districts WHERE name = 'Narsingdi' LIMIT 1), 'active'),
('রাজবাড়ী সদর', 'Rajbari Sadar', (SELECT id FROM districts WHERE name = 'Rajbari' LIMIT 1), 'active'),
('রাজশাহী সদর', 'Rajshahi Sadar', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('রাজনগর', 'Rajnagar', (SELECT id FROM districts WHERE name = 'Moulvibazar' LIMIT 1), 'active'),
('রাজপুতানা', 'Rajputana', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('রামগড়', 'Ramgarh', (SELECT id FROM districts WHERE name = 'Khagrachhari' LIMIT 1), 'active'),
('রামগঞ্জ', 'Ramganj', (SELECT id FROM districts WHERE name = 'Lakshmipur' LIMIT 1), 'active'),
('রামগতি', 'Ramgati', (SELECT id FROM districts WHERE name = 'Lakshmipur' LIMIT 1), 'active'),
('রামপাল', 'Rampal', (SELECT id FROM districts WHERE name = 'Bagerhat' LIMIT 1), 'active'),
('রামপুরা', 'Rampura', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('রানা', 'Rana', (SELECT id FROM districts WHERE name = 'Pirojpur' LIMIT 1), 'active'),
('রাঙামাটি সদর', 'Rangamati Sadar', (SELECT id FROM districts WHERE name = 'Rangamati' LIMIT 1), 'active'),
('রংপুর সদর', 'Rangpur Sadar', (SELECT id FROM districts WHERE name = 'Rangpur' LIMIT 1), 'active'),
('রানীনগর', 'Raninagar', (SELECT id FROM districts WHERE name = 'Naogaon' LIMIT 1), 'active'),
('রানীশংকৈল', 'Ranisankail', (SELECT id FROM districts WHERE name = 'Thakurgaon' LIMIT 1), 'active'),
('রাউজান', 'Raozan', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('রায়পুর', 'Raipur', (SELECT id FROM districts WHERE name = 'Lakshmipur' LIMIT 1), 'active'),
('রূপগঞ্জ', 'Rupganj', (SELECT id FROM districts WHERE name = 'Narayanganj' LIMIT 1), 'active'),
('রূপসা', 'Rupsa', (SELECT id FROM districts WHERE name = 'Khulna' LIMIT 1), 'active'),
('সাভার', 'Savar', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('সদর', 'Sadar', (SELECT id FROM districts WHERE name = 'Rangpur' LIMIT 1), 'active'),
('সদরপুর', 'Sadarpur', (SELECT id FROM districts WHERE name = 'Faridpur' LIMIT 1), 'active'),
('সাঘাটা', 'Saghata', (SELECT id FROM districts WHERE name = 'Gaibandha' LIMIT 1), 'active'),
('সখিপুর', 'Sakhipur', (SELECT id FROM districts WHERE name = 'Tangail' LIMIT 1), 'active'),
('সালথা', 'Saltha', (SELECT id FROM districts WHERE name = 'Faridpur' LIMIT 1), 'active'),
('সান্দ্বীপ', 'Sandwip', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('সাঁথিয়া', 'Santhia', (SELECT id FROM districts WHERE name = 'Pabna' LIMIT 1), 'active'),
('সাপাহার', 'Sapahar', (SELECT id FROM districts WHERE name = 'Naogaon' LIMIT 1), 'active'),
('সরাইল', 'Sarail', (SELECT id FROM districts WHERE name = 'Brahmanbaria' LIMIT 1), 'active'),
('সারিয়াকান্দি', 'Sariakandi', (SELECT id FROM districts WHERE name = 'Bogura' LIMIT 1), 'active'),
('সৎখীরা সদর', 'Satkhira Sadar', (SELECT id FROM districts WHERE name = 'Satkhira' LIMIT 1), 'active'),
('সাতকানিয়া', 'Satkania', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('সাটুরিয়া', 'Saturia', (SELECT id FROM districts WHERE name = 'Manikganj' LIMIT 1), 'active'),
('সাদুল্লাপুর', 'Sedullapur', (SELECT id FROM districts WHERE name = 'Gaibandha' LIMIT 1), 'active'),
('সেনবাগ', 'Senbag', (SELECT id FROM districts WHERE name = 'Noakhali' LIMIT 1), 'active'),
('শাহ আলি', 'Shah Ali', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('শাহবাগ', 'Shahbag', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('শাহজাদপুর', 'Shahajadpur', (SELECT id FROM districts WHERE name = 'Sirajganj' LIMIT 1), 'active'),
('শাহজালাল', 'Shahjalal', (SELECT id FROM districts WHERE name = 'Sylhet' LIMIT 1), 'active'),
('শাহপরান', 'Shahporan', (SELECT id FROM districts WHERE name = 'Sylhet' LIMIT 1), 'active'),
('শাহরাস্তি', 'Shahrasti', (SELECT id FROM districts WHERE name = 'Chandpur' LIMIT 1), 'active'),
('শাজাহানপুর', 'Shajahanpur', (SELECT id FROM districts WHERE name = 'Bogura' LIMIT 1), 'active'),
('শাল্লা', 'Shalla', (SELECT id FROM districts WHERE name = 'Sunamganj' LIMIT 1), 'active'),
('শরণখোলা', 'Sharankhola', (SELECT id FROM districts WHERE name = 'Bagerhat' LIMIT 1), 'active'),
('শরিয়তপুর সদর', 'Shariatpur Sadar', (SELECT id FROM districts WHERE name = 'Shariatpur' LIMIT 1), 'active'),
('শিবচর', 'Shibchar', (SELECT id FROM districts WHERE name = 'Madaripur' LIMIT 1), 'active'),
('শিবগঞ্জ', 'Shibganj', (SELECT id FROM districts WHERE name = 'Bogura' LIMIT 1), 'active'),
('শিবগঞ্জ', 'Shibganj', (SELECT id FROM districts WHERE name = 'Chapainawabganj' LIMIT 1), 'active'),
('শিবপুর', 'Shibpur', (SELECT id FROM districts WHERE name = 'Narsingdi' LIMIT 1), 'active'),
('শেরপুর সদর', 'Sherpur Sadar', (SELECT id FROM districts WHERE name = 'Sherpur' LIMIT 1), 'active'),
('শেরে বাংলা নগর', 'Sher-e-Bangla Nagar', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('শেরপুর', 'Sherpur', (SELECT id FROM districts WHERE name = 'Bogura' LIMIT 1), 'active'),
('শিমুলিয়া', 'Shimulia', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('শিরোমণি', 'Shiromoni', (SELECT id FROM districts WHERE name = 'Khulna' LIMIT 1), 'active'),
('শ্যামনগর', 'Shyamnagar', (SELECT id FROM districts WHERE name = 'Satkhira' LIMIT 1), 'active'),
('শ্যামপুর', 'Shyampur', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('সিঙ্গাইর', 'Singair', (SELECT id FROM districts WHERE name = 'Manikganj' LIMIT 1), 'active'),
('সিংড়া', 'Singra', (SELECT id FROM districts WHERE name = 'Natore' LIMIT 1), 'active'),
('সিরাজগঞ্জ সদর', 'Sirajganj Sadar', (SELECT id FROM districts WHERE name = 'Sirajganj' LIMIT 1), 'active'),
('সিরাজদিখান', 'Sirajdikhan', (SELECT id FROM districts WHERE name = 'Munshiganj' LIMIT 1), 'active'),
('সীতাকুণ্ড', 'Sitakunda', (SELECT id FROM districts WHERE name = 'Chattogram' LIMIT 1), 'active'),
('সোনাগাজী', 'Sonagazi', (SELECT id FROM districts WHERE name = 'Feni' LIMIT 1), 'active'),
('সোনাইমুড়ী', 'Sonaimuri', (SELECT id FROM districts WHERE name = 'Noakhali' LIMIT 1), 'active'),
('সোনারগাঁও', 'Sonargaon', (SELECT id FROM districts WHERE name = 'Narayanganj' LIMIT 1), 'active'),
('শ্রীনগর', 'Sreenagar', (SELECT id FROM districts WHERE name = 'Munshiganj' LIMIT 1), 'active'),
('শ্রীমঙ্গল', 'Sreemangal', (SELECT id FROM districts WHERE name = 'Moulvibazar' LIMIT 1), 'active'),
('শ্রীপুর', 'Sreepur', (SELECT id FROM districts WHERE name = 'Gazipur' LIMIT 1), 'active'),
('সুবর্ণচর', 'Subarnachar', (SELECT id FROM districts WHERE name = 'Noakhali' LIMIT 1), 'active'),
('সুজানগর', 'Sujanagar', (SELECT id FROM districts WHERE name = 'Pabna' LIMIT 1), 'active'),
('সুন্দরগঞ্জ', 'Sundarganj', (SELECT id FROM districts WHERE name = 'Gaibandha' LIMIT 1), 'active'),
('সুনামগঞ্জ সদর', 'Sunamganj Sadar', (SELECT id FROM districts WHERE name = 'Sunamganj' LIMIT 1), 'active'),
('সুরেশ্বর', 'Sureswar', (SELECT id FROM districts WHERE name = 'Gopalganj' LIMIT 1), 'active'),
('সিলেট সদর', 'Sylhet Sadar', (SELECT id FROM districts WHERE name = 'Sylhet' LIMIT 1), 'active'),
('তাহিরপুর', 'Tahirpur', (SELECT id FROM districts WHERE name = 'Sunamganj' LIMIT 1), 'active'),
('তালা', 'Tala', (SELECT id FROM districts WHERE name = 'Satkhira' LIMIT 1), 'active'),
('তালতলি', 'Taltali', (SELECT id FROM districts WHERE name = 'Barguna' LIMIT 1), 'active'),
('তানোর', 'Tanor', (SELECT id FROM districts WHERE name = 'Rajshahi' LIMIT 1), 'active'),
('তারাকান্দা', 'Tarakanda', (SELECT id FROM districts WHERE name = 'Mymensingh' LIMIT 1), 'active'),
('তারাগঞ্জ', 'Taraganj', (SELECT id FROM districts WHERE name = 'Rangpur' LIMIT 1), 'active'),
('টঙ্গী', 'Tongi', (SELECT id FROM districts WHERE name = 'Gazipur' LIMIT 1), 'active'),
('তেঁতুলিয়া', 'Tetulia', (SELECT id FROM districts WHERE name = 'Panchagarh' LIMIT 1), 'active'),
('টেকনাফ', 'Teknaf', (SELECT id FROM districts WHERE name = 'Cox''s Bazar' LIMIT 1), 'active'),
('তেজগাঁও', 'Tejgaon', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('তেরখাদা', 'Terkhada', (SELECT id FROM districts WHERE name = 'Khulna' LIMIT 1), 'active'),
('ঠাকুরগাঁও সদর', 'Thakurgaon Sadar', (SELECT id FROM districts WHERE name = 'Thakurgaon' LIMIT 1), 'active'),
('তিতাস', 'Titas', (SELECT id FROM districts WHERE name = 'Comilla' LIMIT 1), 'active'),
('তংগীবাড়ী', 'Tongibari', (SELECT id FROM districts WHERE name = 'Munshiganj' LIMIT 1), 'active'),
('টুঙ্গিপাড়া', 'Tungipara', (SELECT id FROM districts WHERE name = 'Gopalganj' LIMIT 1), 'active'),
('উখিয়া', 'Ukhia', (SELECT id FROM districts WHERE name = 'Cox''s Bazar' LIMIT 1), 'active'),
('উল্লাপাড়া', 'Ullapara', (SELECT id FROM districts WHERE name = 'Sirajganj' LIMIT 1), 'active'),
('উত্তরা', 'Uttara', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('উত্তরখান', 'Uttarkhan', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('উখিয়া', 'Ukhiya', (SELECT id FROM districts WHERE name = 'Cox''s Bazar' LIMIT 1), 'active'),
('ওয়ারী', 'Wari', (SELECT id FROM districts WHERE name = 'Dhaka' LIMIT 1), 'active'),
('উজিরপুর', 'Wazirpur', (SELECT id FROM districts WHERE name = 'Barisal' LIMIT 1), 'active'),
('জাজিরা', 'Zajira', (SELECT id FROM districts WHERE name = 'Shariatpur' LIMIT 1), 'active'),
('জকিগঞ্জ', 'Zakiganj', (SELECT id FROM districts WHERE name = 'Sylhet' LIMIT 1), 'active'),
('জিয়ানগর', 'Zianagar', (SELECT id FROM districts WHERE name = 'Pirojpur' LIMIT 1), 'active');